replicaCount: 1

image:
  repository: vaultwarden/server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: websocket
      port: 3012
      targetPort: 3012

resources: {}

config:
  YUBICO_SECRET_KEY: "12345678"
  INVITATIONS_ALLOWED: "true"
  DATA_FOLDER: "/data"
  SIGNUPS_ALLOWED: "true"
  WEB_VAULT_ENABLED: "true"
  WEBSOCKET_ENABLED: "true"
  SMTP_SECURITY: "off"
  SHOW_PASSWORD_HINT: "false"
  SMTP_PORT: "25"
  ROCKET_WORKERS: "10"
  ROCKET_PORT: "8080"
  SMTP_HOST: "aspmx.l.google.com"
  SMTP_FROM: "vaultwarden@youremail.fr"
  YUBICO_CLIENT_ID: "123123"

# Shared domain value
domain: "https://your-openshift-route-url"

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

serviceAccount:
  create: true
  name: vaultwarden

rbac:
  create: true

route:
  enabled: true
  tls:
    termination: edge
  wildcardPolicy: None

consoleLink:
  enabled: true
  imageURL: "https://upload.wikimedia.org/wikipedia/commons/8/83/Vaultwarden_icon.svg"
  section: "secret console link"
  text: "Vaultwarden"

