apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  YUBICO_SECRET_KEY: {{ .Values.config.YUBICO_SECRET_KEY | quote }}
  INVITATIONS_ALLOWED: {{ .Values.config.INVITATIONS_ALLOWED | quote }}
  DATA_FOLDER: {{ .Values.config.DATA_FOLDER | quote }}
  DOMAIN: {{ .Values.domain | quote }}
  SIGNUPS_ALLOWED: {{ .Values.config.SIGNUPS_ALLOWED | quote }}
  WEB_VAULT_ENABLED: {{ .Values.config.WEB_VAULT_ENABLED | quote }}
  WEBSOCKET_ENABLED: {{ .Values.config.WEBSOCKET_ENABLED | quote }}
  SMTP_SECURITY: {{ .Values.config.SMTP_SECURITY | quote }}
  SHOW_PASSWORD_HINT: {{ .Values.config.SHOW_PASSWORD_HINT | quote }}
  SMTP_PORT: {{ .Values.config.SMTP_PORT | quote }}
  ROCKET_WORKERS: {{ .Values.config.ROCKET_WORKERS | quote }}
  ROCKET_PORT: {{ .Values.config.ROCKET_PORT | quote }}
  SMTP_HOST: {{ .Values.config.SMTP_HOST | quote }}
  SMTP_FROM: {{ .Values.config.SMTP_FROM | quote }}
  YUBICO_CLIENT_ID: {{ .Values.config.YUBICO_CLIENT_ID | quote }}

