apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-route
spec:
  host: {{ .Values.domain | trimPrefix "https://" }}
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tls.termination }}
  to:
    kind: Service
    name: {{ .Release.Name }}-service
    weight: 100
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
